version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_service
    env_file:
      - credentials.env
    ports:
      - "5434:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./data:/data
      - ./infra_setup/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:

